# -----------------------------------------------------------------
# USER DEFINED OPTIONS
# -----------------------------------------------------------------

# Data properties --------------------------------------------------

dataset:
  name : &dataname 1kplus
  main path : &maindatapath data/
  path : !join [*maindatapath, *dataname, _data_and_labels_outcome_pred.pkl]
  splits path : !join [*maindatapath, *dataname, _clinical_train_test_sets.pkl]
  only treated : no

# All Modeling Properties --------------------------------------------

final performance measures :
  - AUC
  - accuracy
  - average_class_accuracy
  - f1

test size : 0.2

validation score : roc_auc

save options :
  main path : &mainsavepath modeling_results/
  models path : !join [*mainsavepath, *dataname, /models]
  params path : !join [*mainsavepath, *dataname, /params]
  weights path : !join [*mainsavepath, *dataname, /weights]
  scores path : !join [*mainsavepath, *dataname, /performance_scores]
  figures path : !join [*mainsavepath, *dataname, /figures]

# Modeling Properties for non-DL models -----------------------------

models to use :
  - GLM
  - Lasso
  - Elasticnet
  - Catboost
  - MLP


subsampling to use :
  - none
  - random



number of splits : 50

cv folds : 10


# Modeling Properties for DL model --------------------------------

validation size : 0.2

# Tuning parameters ----------------------------------------------

tuning parameters :
  GLM : None

  Lasso :
    C : [0.1, 0.1207, 0.1456, 0.1758, 0.2121, 0.256, 0.3089, 0.3728, 0.4498, 0.5429, 0.6551, 0.7906, 0.9541, 1.1514, 1.3895, 1.6768, 2.0236, 2.4421, 2.9471, 3.5565,
         4.2919, 5.1795, 6.2506, 7.5431, 9.103, 10.9854, 13.2571, 15.9986, 19.307, 23.2995, 28.1177, 33.9322, 40.9492, 49.4171, 59.6362, 71.9686, 86.8511, 104.8113,
         126.4855, 152.6418, 184.207, 222.2996, 268.2696, 323.7458, 390.694, 471.4866, 568.9866, 686.6488, 828.6428, 1000.0]

  Elasticnet :
    l1_ratio : [0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95]
    alpha : [0.00001, 0.00004, 0.00016, 0.0006, 0.0025, 0.01, 0.04, 0.16, 0.63, 2.5, 10.0]

  Catboost :
    l2_leaf_reg : [3.,10.,100.,500.]
    depth : [2.,4.]
    leaf_estimation_iterations : [1.,2.]
    bagging_temperature : [0.6,0.8,1.]
    learning_rate : [0.03,0.1,0.3]

  MLP :
    batch_size : [16,32]
    num_neurons : [5,10,15,20]
    learning_rate : [0.001, 0.01]
    dropout_rate : [0.1, 0.2]
    l1_ratio : [0.0001,0.001]


# -----------------------------------------------------------------
# DEFAULT OPTIONS
# -----------------------------------------------------------------

# Model hyperparameters:

hyperparameters:
  GLM :
    C : 100000000000000
    fit_intercept : no
    penalty : l1
    solver : saga
    tol : 0.001
    max_iter : 10000
    n_jobs : -1

  Lasso :
    fit_intercept : no
    penalty : l1
    solver : saga
    tol : 0.001
    max_iter : 10000
    n_jobs : -1

  Elasticnet :
    loss : log
    penalty : elasticnet
    fit_intercept : no
    tol : 0.001
    max_iter : 10000
    n_jobs : -1

  Catboost :
    od_type : Iter
    od_wait : 40

  MLP :
    epochs : 50
    iter_patience : 2
    hidden_activation : 'relu'
    out_activation : 'sigmoid'
    loss_func : 'binary_crossentropy'
    optimizer : 'adam'
    weight_init : 'uniform'
